// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6rGwV4UvVwlVaYonbVkVYqLeccPtw1os',
    appId: '1:551719042382:web:d82e753cba362e96e2721f',
    messagingSenderId: '551719042382',
    projectId: 'ecanteen-362458302100-nadhif',
    authDomain: 'ecanteen-362458302100-nadhif.firebaseapp.com',
    storageBucket: 'ecanteen-362458302100-nadhif.firebasestorage.app',
    measurementId: 'G-BJTMJKHF37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCJb9dNxCMqUuqfynVtgxchskuzAZtUZo',
    appId: '1:551719042382:android:14ce77e328c4803de2721f',
    messagingSenderId: '551719042382',
    projectId: 'ecanteen-362458302100-nadhif',
    storageBucket: 'ecanteen-362458302100-nadhif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuN3Riw5wHEN_CICSCEbGbaclKNLHleN8',
    appId: '1:551719042382:ios:db4b986afa4db075e2721f',
    messagingSenderId: '551719042382',
    projectId: 'ecanteen-362458302100-nadhif',
    storageBucket: 'ecanteen-362458302100-nadhif.firebasestorage.app',
    iosBundleId: 'com.example.eCanteen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuN3Riw5wHEN_CICSCEbGbaclKNLHleN8',
    appId: '1:551719042382:ios:db4b986afa4db075e2721f',
    messagingSenderId: '551719042382',
    projectId: 'ecanteen-362458302100-nadhif',
    storageBucket: 'ecanteen-362458302100-nadhif.firebasestorage.app',
    iosBundleId: 'com.example.eCanteen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6rGwV4UvVwlVaYonbVkVYqLeccPtw1os',
    appId: '1:551719042382:web:c94c45d523c0dec9e2721f',
    messagingSenderId: '551719042382',
    projectId: 'ecanteen-362458302100-nadhif',
    authDomain: 'ecanteen-362458302100-nadhif.firebaseapp.com',
    storageBucket: 'ecanteen-362458302100-nadhif.firebasestorage.app',
    measurementId: 'G-STFLDRY7H2',
  );
}
